# Generated by Django 3.2.6 on 2021-09-16 11:30

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_card_container', '0002_auto_20210916_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='listpage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
