# Generated by Django 3.2.6 on 2021-09-16 11:31

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_card_container', '0003_listpage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listpage',
            name='body',
        ),
        migrations.AddField(
            model_name='detailpage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
