# Generated by Django 3.2.6 on 2021-09-16 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_card_container', '0004_auto_20210916_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailpage',
            name='body',
        ),
    ]
