# Generated by Django 3.2.6 on 2021-09-16 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_card_container', '0006_detailpage_body'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetailPageListCategory',
            new_name='DetailPageCategory',
        ),
    ]
