# Generated by Django 3.2.6 on 2021-09-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_card_container', '0007_rename_detailpagelistcategory_detailpagecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='detailpage',
            name='hero_content',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
