# Generated by Django 3.2.6 on 2021-09-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_card_container', '0008_auto_20210916_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpage',
            name='hero_content',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
