# Generated by Django 3.2.6 on 2021-09-16 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_card_container', '0009_alter_detailpage_hero_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailpage',
            name='hero_content',
        ),
    ]
