# Generated by Django 3.2.6 on 2021-09-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_card_container', '0010_remove_detailpage_hero_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailpage',
            name='hero_content',
            field=models.BooleanField(default=False),
        ),
    ]
