# Generated by Django 3.2.6 on 2021-09-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_card_container', '0011_detailpage_hero_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailpage',
            old_name='hero_content',
            new_name='hero_content_bool',
        ),
        migrations.AddField(
            model_name='detailpage',
            name='hero_super_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
