# Generated by Django 3.2.6 on 2021-09-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_card_container', '0012_auto_20210916_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailpage',
            name='blurb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
