# Generated by Django 3.2.6 on 2021-09-17 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_card_container', '0015_auto_20210917_0759'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CardCategory',
            new_name='Category',
        ),
        migrations.AddField(
            model_name='detailpagecategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='main_card_container.category'),
        ),
        migrations.AlterUniqueTogether(
            name='detailpagecategory',
            unique_together={('page', 'category')},
        ),
        migrations.RemoveField(
            model_name='detailpagecategory',
            name='card_category',
        ),
    ]
