# Generated by Django 3.2.6 on 2021-09-17 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_card_container', '0016_auto_20210917_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpagecategory',
            name='category',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='main_card_container.category'),
        ),
    ]
