# Generated by Django 3.2.7 on 2021-10-20 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_card_container', '0024_alter_detailpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpagecategory',
            name='category',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='main_card_container.category'),
        ),
    ]
