# Generated by Django 3.2.7 on 2021-10-20 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_card_container', '0025_alter_detailpagecategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailpagecategory',
            name='category',
            field=models.ForeignKey(blank='False', null='False', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='main_card_container.category'),
        ),
    ]
