# Generated by Django 3.2.6 on 2021-09-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingListEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
