# Generated by Django 3.2.6 on 2021-09-23 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0002_mailinglistentries'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MailingListEntries',
            new_name='MailingListEntry',
        ),
    ]
