# Generated by Django 3.2.6 on 2021-09-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0003_rename_mailinglistentries_mailinglistentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailingListEntry',
        ),
    ]
