# Generated by Django 3.2.6 on 2021-09-23 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('mailing_list', '0007_mailinglist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MailingList',
        ),
        migrations.DeleteModel(
            name='MailingListPage',
        ),
    ]
