# Generated by Django 3.2.7 on 2021-09-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0010_mailinglistpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
