# Generated by Django 3.2.7 on 2021-09-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0011_alter_mailinglist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='email_address',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
