# Generated by Django 3.2.6 on 2021-09-21 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_card_container', '0021_alter_listpage_discipline'),
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='music_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='music_page_fk', to='main_card_container.listpage', verbose_name='music_page'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='tech_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tech_page_fk', to='main_card_container.listpage', verbose_name='tech_page'),
        ),
    ]
