# Generated by Django 3.2.6 on 2021-09-21 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('landing', '0002_auto_20210921_0615'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LandingPage',
        ),
    ]
